# Generated by Django 4.1.3 on 2022-11-13 03:07

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Representa una migración inicial generada por Django.

    Attributes:
        dependencies (list): Lista de dependencias de migración para esta migración.
        operations (list): Lista de operaciones que se realizarán durante esta migración.

    """

    initial = True  # Indica que esta es una migración inicial.

    dependencies = []  # No tiene dependencias, ya que es una migración inicial.

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
