# Generated by Django 4.1.2 on 2022-11-17 13:43

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración realiza tres operaciones: renombrar los modelos "Images" a "Image", 
    "Masks" a "Mask" y agregar un campo "status" al modelo "Experimento".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Masks',
            new_name='Mask',
        ),
        migrations.AddField(
            model_name='experimento',
            name='status',
            field=models.CharField(default='Finalizado', max_length=20),
            preserve_default=False,
        ),
    ]
