# Generated by Django 4.1.2 on 2022-11-17 20:22

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración modifica los campos "fecha_inicio", "frecuencia" y "status" en el modelo "Experimento".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0002_rename_images_image_rename_masks_mask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='frecuencia',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='experimento',
            name='status',
            field=models.CharField(default='Creado', max_length=20),
        ),
    ]
