# Generated by Django 4.1.2 on 2022-11-17 20:24

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración modifica el campo "status" en el modelo "Experimento".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0003_alter_experimento_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='status',
            field=models.CharField(default='Creado', editable=False, max_length=20),
        ),
    ]
