# Generated by Django 4.1.2 on 2022-11-17 20:35

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración modifica el campo "fecha_inicio" en el modelo "Experimento".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0005_alter_experimento_cantidad_imagenes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
