# Generated by Django 4.1.2 on 2022-11-17 20:37

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración modifica el campo "cantidad_imagenes" en el modelo "Experimento".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0006_alter_experimento_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimento',
            name='cantidad_imagenes',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
