# Generated by Django 4.1.3 on 2022-11-26 21:44

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración agrega un nuevo campo "progreso" al modelo "Experimento".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0008_alter_experimento_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='progreso',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
