# Generated by Django 4.1.3 on 2022-11-27 05:55

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración altera dos campos de fecha en los modelos "Image" y "Mask".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0009_experimento_progreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mask',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
