# Generated by Django 4.1.3 on 2023-03-03 02:58

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración altera un campo de fecha en el modelo "Semillas".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0010_alter_image_fecha_alter_mask_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semillas',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
