# Generated by Django 4.1.3 on 2023-03-22 14:14

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Clase de migración generada por Django que representa un cambio en la base de datos.
    La migración agrega un nuevo campo "imagenes_capturadas" al modelo "Experimento".

    Atributos:
        - `dependencies` (list): Una lista de dependencias de otras migraciones.
        - `operations` (list): Una lista de operaciones que se realizarán durante la migración.
    """

    dependencies = [
        ('experimentos', '0011_alter_semillas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimento',
            name='imagenes_capturadas',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
